Application base and with exoplayer
DF5HSE/AndroidVideoPlayer pull request #4
Opened 2021-04-27 21:51 UTC by DF5HSE

2021-04-27 21:54 UTC, DF5HSE commented
https://trello.com/c/mAVLGRF7

2021-05-03 10:20 UTC, tilacyn requested changes

2021-05-03 10:20 UTC, tilacyn commented on app/src/main/java/Adapter/VideoAdapter.java
> +    Context context;
Поля в основном должны быть private, в данном случае можно еще и final

2021-05-03 10:20 UTC, tilacyn commented on app/src/main/java/Adapter/VideoAdapter.java
> +        RelativeLayout rl_select;
Есть конвенция, что нейминг в Джаве делается CamelCase-ом)

2021-05-03 10:20 UTC, tilacyn commented on app/src/main/java/com/example/avp/ui/MainActivity.java
> +            case PERMISSION_REQUEST_CODE:
Этот switch можно переделать на if-else

2021-05-03 10:20 UTC, tilacyn commented on app/src/main/java/com/example/avp/ui/MainActivity.java
> +    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
В целом следует избегать длинных методов, здесь можно вынести определение флажка allowed в отдельный метод

2021-05-03 10:20 UTC, tilacyn commented on app/src/main/java/com/example/avp/ui/MainActivity.java
> +                if (shouldShowRequestPermissionRationale(Manifest.permission.WRITE_EXTERNAL_STORAGE)){
Три вложенных ифа - это очень много, надо вынести else блок в отдельный метод

2021-05-03 10:20 UTC, tilacyn commented on app/src/main/java/com/example/avp/ui/MainActivity.java
> +            case R.id.navigation_video_from_device:
Здесь обработку каждого кейса тоже следует вынести в отдельный метод

2021-05-03 10:20 UTC, tilacyn commented on app/src/main/java/com/example/avp/ui/VideoPlayerActivity.java
> +    VideoView videoView;
Надо сделать поля private (final) и соблюдать naming конвенцию (CamelCase)

2021-05-03 10:20 UTC, tilacyn commented on app/src/main/java/com/example/avp/ui/MainActivity.java
> +                        fragment = new VideoByLinkFragment();
Кажется мы столкнулись с большим количеством инстанцирования в коде. Предлагаю использовать Dependency Injection, например с помощью библиотеки Dagger 2. Можно это сделать отдельной задачей, конечно

2021-05-14 14:51 UTC, tilacyn approved these changes

2021-05-21 11:52 UTC, merged