Own player implementation
DF5HSE/AndroidVideoPlayer pull request #5
Opened 2021-05-20 22:33 UTC by DF5HSE

2021-05-20 22:37 UTC, DF5HSE commented
https://trello.com/c/unJ0IMTI

2021-05-26 01:06 UTC, DF5HSE commented
Код ужасный, пока можешь особо не смотреть, я в четверг, скорее всего сяду и буду все поправлять, в том числе то, о чем мы с тобой на созвоне говорили

2021-05-26 01:06 UTC, DF5HSE commented
https://trello.com/c/jQ9SeB5V

2021-06-07 20:18 UTC, tilacyn requested changes

2021-06-07 20:18 UTC, tilacyn commented on app/src/main/java/com/example/avp/player/AVPMediaMetaData.java
> +public class AVPMediaMetaData {
можно использовать lombok, пример https://github.com/DF5HSE/AndroidVideoPlayer/pull/7/files#diff-06f15bcbad8ff9df19a4707b62972254943d2238e37c330e6c6e683787c58e23

2021-06-07 20:18 UTC, tilacyn commented on app/src/main/java/com/example/avp/player/ExoPlayerActivity.java
> +        player.addListener(new Player.EventListener() {
Очень большой метод, надо бы его разбить, можно классы выделить вместо анонимных

2021-06-07 20:18 UTC, tilacyn commented on app/src/main/java/com/example/avp/player/ExoPlayerModel.java
> +        if (isYoutubeUrl(linkOnVideo)) {
этот разбор случаев можно переделать через интерфейсы

2021-06-07 20:18 UTC, tilacyn commented on app/src/main/java/com/example/avp/player/ExoPlayerModel.java
> +        return Observable.fromCallable(() ->
Здесь fromCallable лучше заменить на just

2021-06-07 20:18 UTC, tilacyn commented on app/src/main/java/com/example/avp/player/ExoPlayerModel.java
> +        new YouTubeExtractor(context) {
Этот анонимный класс точно нужно в отдельный класс (заодно можно реализовать интерфейс который возвращает observable)

2021-06-07 20:18 UTC, tilacyn commented on app/src/main/java/com/example/avp/player/HeadsetButtonReceiver.java
> +    interface onHeadsetListener{
интерфейсы и классы надо именовать с большой буквы

2021-06-11 18:45 UTC, merged